// AUTOGENERATED TYPINGS, these should not be edited.
declare namespace StylesLessNamespace {
  export interface IStylesLess {
    debugOutput: string;
    gestureArea: string;
  }
}

declare const StylesLessModule: StylesLessNamespace.IStylesLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesLessNamespace.IStylesLess;
};

export = StylesLessModule;
