// AUTOGENERATED TYPINGS, these should not be edited.
declare namespace StylesLessNamespace {
  export interface IStylesLess {
    buttonHide: string;
    cameraControls: string;
    cameraControlsWrapper: string;
    cameraMode: string;
    cameraSwitch: string;
    cameraWrapper: string;
    canvas: string;
    carouselIcon: string;
    counter: string;
    exit: string;
    exitIcon: string;
    flashIcon: string;
    hideCounter: string;
    icon: string;
    icons: string;
    innerVideo: string;
    mediaPreviewIcon: string;
    modeOptions: string;
    moveLeft: string;
    moveRight: string;
    recordingCounter: string;
    selectEl: string;
    shutter: string;
    shutterIcon: string;
    startRecordingIcon: string;
    stopRecordingIcon: string;
    toggleCamera: string;
    toolbar: string;
    topNav: string;
    torchIcon: string;
    viewfinder: string;
    zoom: string;
  }
}

declare const StylesLessModule: StylesLessNamespace.IStylesLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesLessNamespace.IStylesLess;
};

export = StylesLessModule;
